// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need a direct (non-pooled) connection — Supabase's pooler
    // (Supavisor/PgBouncer, used for DATABASE_URL at runtime) doesn't
    // support the session-level operations `migrate` relies on. Falls back
    // to DATABASE_URL for setups that don't split the two (e.g. a plain
    // local Postgres with no pooler in front of it).
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
